# name the compiler
CPP = wpp386
CC = wcc386
WL = wlib
ASM = JWasm

OBJETS1 =	PCX.OBJ		LOADPCX.OBJ	SAVEPCX.OBJ


!ifeq BT NT
CFLAGS	= /D_WIN32 /fh=NT.PCH
AFLAGS	= /D_WIN32
LIB     = NT_FIOS
OBJETS2 =
!else
CFLAGS	= /D_DOS4GW /fh=DOS.PCH
AFLAGS	= /D_DOS4GW
LIB     = DOS_FIOS
OBJETS2 =
!endif

CFLAGS += /6s /d3 /od /s /wx /mf /hd /DLIB_LOCAL /bt=$(BT) /zp1 /v
LFLAGS  = /c /b /l
AFLAGS += /DSTACK_CALL /nologo /Cx /c /WX /Zd /omf /Zp1 /Fl /Fd

#.SILENT

$(LIB).LIB: $(OBJETS1) $(OBJETS2)
	*$(WL) $(LFLAGS) $(LIB) $?

.cpp.obj:
	$(CPP) $* $(CFLAGS)

.c.obj:
	$(CC) $* $(CFLAGS)

.asm.obj:
	$(ASM) $(AFLAGS) $*.ASM
