# name the compiler
CPP = wpp386
CC = wcc386
WL = wlib
ASM = JWasm

OBJETS1 =	ANIM.OBJ	BODY.OBJ	CLEAR.OBJ	FRAME.OBJ	&
		INTANIM.OBJ	INTERDEP.OBJ	INTFRAME.OBJ	LIBINIT.OBJ	&
		STOFRAME.OBJ	TEXTURE.OBJ

!ifeq BT NT
CFLAGS	= /D_WIN32 /fh=NT.PCH
AFLAGS	= /D_WIN32
LIB     = NT_ANIR
OBJETS2 =
!else
CFLAGS	= /D_DOS4GW /fh=DOS.PCH
AFLAGS	= /D_DOS4GW
LIB     = DOS_ANIR
OBJETS2 =
!endif

CFLAGS += /5r /d3 /otexan /s /wx /mf /hd /DLIB_LOCAL /bt=$(BT) /v
LFLAGS  = /c /b /l
AFLAGS += /DREG_CALL /nologo /Cx /c /WX /Zd /omf /Fl /Fd

#.SILENT

$(LIB).LIB: $(OBJETS1) $(OBJETS2)
	*$(WL) $(LFLAGS) $(LIB) $?

.cpp.obj:
	$(CPP) $* $(CFLAGS)

.c.obj:
	$(CC) $* $(CFLAGS)

.asm.obj:
	$(ASM) $(AFLAGS) $*.ASM
