# name the compiler
CPP = wpp386
CC = wcc386
WL = wlib
ASM = ml

OBJETS1 =	ANIM.OBJ	BODY.OBJ	CLEAR.OBJ	FRAME.OBJ	&
		INTANIM.OBJ	INTERDEP.OBJ	INTFRAME.OBJ	LIBINIT.OBJ	&
		STOFRAME.OBJ	TEXTURE.OBJ

!ifeq BT NT
CFLAGS	= /D_WIN32 /fh=NT.PCH
AFLAGS	= /D_WIN32
LIB     = NT_ANIS
OBJETS2 =
!else
CFLAGS	= /D_DOS4GW /fh=DOS.PCH
AFLAGS	= /D_DOS4GW
LIB     = DOS_ANIS
OBJETS2 =
!endif

CFLAGS += /6s /d3 /oneatxz /s /wx /mf /hd /DLIB_LOCAL /bt=$(BT) /zp8 /v
LFLAGS  = /c /b /l
AFLAGS += /DSTACK_CALL /nologo /Cx /Zi /c /WX /Sa /Zd /Cp /omf

#.SILENT

$(LIB).LIB: $(OBJETS1) $(OBJETS2)
	*$(WL) $(LFLAGS) $(LIB) $?

.cpp.obj:
	$(CPP) $* $(CFLAGS)

.c.obj:
	$(CC) $* $(CFLAGS)

.asm.obj:
	$(ASM) $(AFLAGS) $*.ASM
