# name the compiler
CPP = wpp386
CC = wcc386
WL = wlib
ASM = JWasm

OBJETS=	AFF_OBJ.OBJ


!ifeq BT NT
DEF	= _WIN32
LIB     = NT_OBJ
!else
DEF	= _DOS4GW
LIB     = DOS_OBJ
!endif

CFLAGS = /6s /d3 /od /s /wx /mf /hd /DLIB_LOCAL /bt=$(BT) /zp1 /v
LFLAGS = /c /b /l
AFLAGS = /DSTACK_CALL /nologo /Cx /c /WX /D$(DEF) /Zd /omf /Zp1 /Fl /Fd

#.SILENT

$(LIB).LIB: $(OBJETS)
	*$(WL) $(LFLAGS) $(LIB) $?

.c.obj:
	$(CC) $* $(CFLAGS)

.asm.obj:
	$(ASM) $(AFLAGS) $*.ASM
