CP = wpp386
CC = wcc386
WL = wlib
LL = wlink
ASM = ml
PCHDIR =

AFLAGS  = /Cx /Zi /c /WX /Sa /nologo
CFLAGS  = /oneatxz /zp8 /6s /s /wx /bt=DOS /fh=$(PCHDIR)lba.pch /DDOS4GW /DDEBUG_TOOLS /d3
LLFLAGS = SYSTEM dos4g OP CASEEXACT,STACK=7000,DOSSEG DEBUG DWARF ALL

LIB386_PATH = ..\..\LIB386
LIBS  = $(LIB386_PATH)\SYSTEM\DOS_SYSS.LIB
LIBS += $(LIB386_PATH)\SVGA\DOS_SVGS.LIB

#.SILENT

.EXTENSIONS:
.EXTENSIONS: .exe .obj .asm .c .cpp

VERSION	= version.obj

OBJETS  = main.obj input.obj config.obj

EXE     = config

# This is the GNU Make equivalent of CURDIR :=
CURDIR   = $+ $(%cdrive):$(%cwd) $-

$(EXE).exe: $(LIBS) $(OBJETS)
	$(LL) NAME $@ $(LLFLAGS) Library { $LIBS } FILE { $OBJETS }

$(LIBS):
	cd $^:
	$(MAKE) "BT=DOS"
	@cd $(CURDIR)

.c.obj :
	$(CC) $^& $(CFLAGS)

.cpp.obj :
	$(CP) $^& $(CFLAGS)

.asm.obj :
	$(ASM) $(AFLAGS) $^&.ASM

