CP = wpp386
CC = wcc386
WL = wlib
LL = wlink
ASM = JWasm
PCHDIR =

AFLAGS  = /DSTACK_CALL /nologo /Cx /c /WX /Zd /omf /Zp1 /Fl /Fd
CFLAGS  = /6s /oneatxz /zp1 /s /wx /mf /bt=DOS /fh=$(PCHDIR)lba.pch /DDOS4GW /DDEBUG_TOOLS /d3
LLFLAGS = SYSTEM dos4g OP CASEEXACT,STACK=7000,SYMF,MAP,DOSSEG,VERBOSE DEBUG DWARF ALL

LIB386_PATH = ..\..\LIB386
LIBS  = $(LIB386_PATH)\AIL\DOS_AILS.LIB
LIBS += $(LIB386_PATH)\POL_WORK\DOS_POLY.LIB
LIBS += $(LIB386_PATH)\SVGA\DOS_SVGS.LIB
LIBS += $(LIB386_PATH)\SYSTEM\DOS_SYSS.LIB

#.SILENT

.EXTENSIONS:
.EXTENSIONS: .exe .obj .asm .c .cpp

VERSION	= version.obj

OBJETS  = main.obj input.obj config.obj

BUILD_DIR = BUILD
EXE     = config

# This is the GNU Make equivalent of CURDIR :=
CURDIR   = $+ $(%cdrive):$(%cwd) $-

$(BUILD_DIR)\$(EXE).exe: $(LIBS) $(OBJETS)
	$(LL) NAME $@ $(LLFLAGS) Library { $LIBS } FILE { $OBJETS }

$(LIBS):
	cd $^:
	$(MAKE) "BT=DOS"
	@cd $(CURDIR)

.c.obj :
	$(CC) $^& $(CFLAGS)

.cpp.obj :
	$(CP) $^& $(CFLAGS)

.asm.obj :
	$(ASM) $(AFLAGS) $^&.ASM

clean: .SYMBOLIC
	@cd $(CURDIR)\..\..
	del /s /q *.obj
	del /s /q *.lib
	del /s /q *.err
	del /s /q *.ld
	del /s /q *.map
	del /s /q *.pch
	del /s /q *.lst
	del /s /q *.def
	@cd $(CURDIR)
